import _ from "lodash";
import React from "react";
import { Grid, Container, Header } from "semantic-ui-react";
import "semantic-ui-css/semantic.min.css";

class ContentPolicies extends React.Component {
    render() {
        return (
            <Grid container>
                <Grid.Row centered style={{ padding: "50pt 0 0 0" }}>
                    <Container fluid textAlign="left">
                        <Header as="h2">
                            The Nature of vibecheck's Content
                        </Header>
                        <p>
                            With the goal of analysing information gathered from
                            the public discussions on the open web,{" "}
                            <em>vibecheck</em> does not filter the data that is
                            analysed and delivered to users upon the search of a
                            query. However, this means that disagreeable,
                            inappropriate, false, inflammatory, or unacceptable
                            language may be analysed and may appear when a
                            search is performed. Furthermore, this kind of data
                            may appear for search topics that may seem free of
                            objectionable discussion. Please be advised that
                            this tool will search the entirety of the sites that
                            it indexes and that anything that appears upon the
                            completion of a search is not necesarily
                            representative of the views or opinions of this
                            site's creators. In fact, all data shown upon a
                            search is generated by users from the sites that{" "}
                            <em>vibecheck</em> indexes; no results have been
                            created or modified by the developers of this site.
                            <em> Proceed with caution.</em>
                        </p>

                        <Header as="h2">The Sentiment Score</Header>
                        <p>
                            At times, the sentiment score may seem to return
                            strange or annoyingly-neutral results. This is
                            normal; we're taking into account any comment that
                            the tool finds during processing, so a plethora of
                            negative sentiment may end up canceled out by a
                            plethora of positive sentiment, leaving you with a
                            fairly neutral score. Additonally, you may find that
                            the score and results change between multiple
                            searches of the same query, even within a few
                            minutes of each other. This is also normal; the
                            primary cause of this variance are the interfaces
                            (APIs) we're using to gather data from platforms. A
                            search of a term on a certain platform will often
                            yield differing results due to a variety of
                            limitations present in the API that allows us to
                            obtain this data, so the same search may lead to the
                            analysis of different datasets.
                        </p>

                        <Header as="h2">Privacy Policy</Header>
                        <p>
                            We care about the privacy of our users. Thus, we
                            collect the minimum amount of information required
                            to keep this site working as intended. Each search
                            and its results are recorded; however, no personally
                            identifying nformation is associated with any of
                            these searches. Furthermore, we collect no
                            personally identifying information upon any other
                            action taken on the site, nor do we use cookies.
                        </p>
                    </Container>
                </Grid.Row>
            </Grid>
        );
    }
}

export default ContentPolicies;
